#!/usr/bin/env python3
"""
Generates the two iPhone shortcuts as signed .shortcut files.

- "Compress Photos": share-sheet shortcut that stages the still photos in
  a-Shell (Live Photos and videos are skipped) and runs jxlbatch (see
  ../README.md).
- "JXL-Import": started by a-Shell when encoding is done; saves the JXL files
  to Photos and cleans up.

The Mac shortcuts are generated by build_mac_shortcuts.py; what both share
(text encoding, built-in actions, the quality list, the still-photo filter) is
in wf.py.

a-Shell's actions (and a few built-in ones whose parameter names vary between
iOS versions) are copied from a real shortcut built on the iPhone and fetched
through its iCloud link: scripts/sample/JXL Sample.plist (see --fetch). If the
sample lacks one of those actions, the script stops with an error instead of
writing a shortcut that won't work.

Usage::

    build_shortcuts.py --guess [--no-sign]
    build_shortcuts.py --fetch https://www.icloud.com/shortcuts/<id>
    build_shortcuts.py [--no-sign]
"""

import argparse
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import wf  # noqa: E402
from wf import (  # noqa: E402
    DEFAULT_QUALITY,
    EFFORT,
    HELP_URL,
    OBJ,
    ORIGINALS_ALBUM,
    QUALITY_PRESETS,
    REPEAT_INDEX,
    REPEAT_ITEM,
    SHORTCUT_INPUT,
    VERSION,
    Ref,
    Sample,
    attachment,
    choose_quality,
    collect_in_album,
    copy_to_albums,
    keep_still_photos,
    output_of,
    plain_or_text,
    text,
    variable,
    workflow,
)

__all__ = [
    'DEFAULT_QUALITY',
    'EFFORT',
    'OBJ',
    'QUALITY_PRESETS',
    'Ref',
    'Sample',
    'VERSION',
    'attachment',
    'output_of',
    'plain_or_text',
    'text',
    'variable',
    'workflow',
]

SAMPLE = HERE / 'sample' / 'JXL Sample.plist'
DIST = HERE.parent / 'dist'
OUT = HERE.parent / 'build' / 'shortcuts'

NAME_A = 'Compress Photos'
NAME_B = (
    'JXL-Import'  # a-Shell starts it by name; no spaces, so no URL escaping
)

# ---------------------------------------------------------------------------
# Sample handling


def fetch_sample(link):
    wf.fetch_sample(link, SAMPLE)


# a-Shell's app ID (a-Shell.xcodeproj).
ASHELL_BUNDLE_ID = 'AsheKube.app.a-Shell'


def guessed_workflow():
    """
    Hand-written templates for --guess, used when no real sample exists.

    a-Shell's actions are stored as "AsheKube.app.a-Shell.<Intent>" with only
    their own parameters (names from a-Shell's
    Base.lproj/Intents.intentdefinition), as in shortcuts shared in a-Shell's
    GitHub issues (#74, #279, #311, #423, #439, #546). Adding an
    IntentAppDefinition block makes them "Unknown Action".
    """

    def ashell(intent, params):
        return wf.action(
            f'{ASHELL_BUNDLE_ID}.{intent}', {'ShowWhenRun': False, **params}
        )

    return wf.guessed_workflow([
        ashell('PutFileIntent', {}),
        ashell('GetFileIntent', {}),
        ashell(
            'ExecuteCommandIntent', {'command': 'ls', 'Show-command': True}
        ),
    ])


# ---------------------------------------------------------------------------
# Actions


class Builder(wf.Builder):
    """The shared actions plus a-Shell's."""

    # a-Shell's parameter names are from its Base.lproj/Intents.intentdefinition.
    # Text parameters are stored as plain strings unless they contain a
    # variable, as the Shortcuts app does.
    def ashell_put_file(self, ref):
        a = self.sample.template('PutFileIntent')
        return self.add(a, {'file': attachment(ref), 'overwrite': True})

    def ashell_get_file(self, *name, error_if_missing=True):
        a = self.sample.template('GetFileIntent')
        # copyFile: return the data, not a link (a-Shell's iOS 18 workaround
        # for files deleted after being shown). Without errorIfNotFound, a
        # missing file gives no output.
        params = {
            'fileName': plain_or_text(*name),
            'errorIfNotFound': error_if_missing,
            'copyFile': True,
        }
        return output_of(self.add(a, params), 'File')

    def ashell_execute(self, *command, keep_going, open_app):
        """
        One a-Shell command text; several commands go on separate lines.

        open_app: 'open' (run in a-Shell, needed for WebAssembly) or 'close'
        (run in the background, for built-in commands like rm).
        """
        a = self.sample.template('ExecuteCommandIntent')
        params = {
            'command': plain_or_text(*command),
            'openWindow': open_app,
            'keepGoing': keep_going,
            'Show-command': True,
        }
        return self.add(a, params)


# ---------------------------------------------------------------------------
# The two shortcuts


def run_jxlbatch(b, quality, then):
    """
    a-Shell command: run jxlbatch, then the command ``then``.

    When this launches a-Shell, a-Shell restores its last session (its folder
    too) while it starts these commands, and its WebAssembly engine may still
    be loading, which ends jxlbatch before it runs. So wait 2 s, change to the
    Shortcuts folder (~shortcuts, where Put File saves), and run jxlbatch; then
    run it with --retry, which does nothing if the first run started (it
    created jxl_started). Not through dash: a-Shell adds ".wasm" to a command's
    name, dash doesn't, so it can't find jxlbatch.

    The variable Skipped Echo (an echo of what the shortcut skipped, set by
    keep_still_photos only when something was) is printed before and after the
    batch; unset, it leaves an empty line, which a-Shell ignores.
    """
    echo = variable('Skipped Echo')
    b.ashell_execute(
        'sleep 2\ncd ~shortcuts\n',
        echo,
        '\njxlbatch -q ',
        quality,
        f' -e {EFFORT} jxl_job.txt\njxlbatch --retry -q ',
        quality,
        f' -e {EFFORT} jxl_job.txt\n',
        echo,
        '\n' + then,
        keep_going=False,
        open_app='open',
    )


def save_results(b, originals=None, album=None):
    """
    Saves the JPEG XL files listed in jxl_done.txt to Photos, each also to the
    albums its original is in.

    Each line is "file|index|delete or keep|name". With ``originals`` (the
    staged photos) and ``album`` (a text ref holding ORIGINALS_ALBUM), the
    albums are read from the original at the line's index, and that original is
    collected in the album (collect_in_album). The flag is jxlbatch's: "keep"
    means the JPEG XL lacks the original's HDR, which a-Shell's output says
    too; it doesn't change what happens here. Without ``originals``, the albums
    are read from jxl_albums_<index>.txt, one album name per line, if that file
    exists. Returns the number of photos saved.
    """
    lines = b.split(b.text_from_input(b.ashell_get_file('jxl_done.txt')), '\n')

    def per_file():
        parts = b.split(REPEAT_ITEM, '|')
        file_name = b.item_from_list(parts, 'First Item')
        photo_name = b.item_from_list(parts, 'Last Item')
        saved = b.save_to_photos(
            b.set_name(b.ashell_get_file(file_name), photo_name)
        )
        index = b.item_at_index(parts, 2)

        def add_to_albums(albums):
            copy_to_albums(b, saved, albums)

        if originals:
            original = b.item_at_index(originals, index)
            albums = b.photo_albums(original)
            add_to_albums(albums)
            collect_in_album(b, original, album, albums)
        else:
            albums_file = b.ashell_get_file(
                'jxl_albums_', index, '.txt', error_if_missing=False
            )
            b.if_has_value(
                albums_file,
                lambda: add_to_albums(
                    b.split(b.text_from_input(albums_file), '\n')
                ),
                lambda: None,
            )

    b.repeat_each(lines, per_file)
    # Not the Repeat Results: a photo in no album adds nothing to those. A
    # failed save stops the shortcut, so every line here was saved.
    return b.count(lines)


CLEANUP = 'rm -f jxl_in_* jxl_out_* jxl_albums_* jxl_job.txt jxl_done.txt jxl_started'


def build_compress(sample):
    b = Builder(sample)
    b.comment(
        f'{NAME_A} {VERSION}. '
        'Converts photos to JPEG XL with a-Shell (jxlbatch), keeping their metadata. '
        'Only still photos are converted: Live Photos and videos are skipped. '
        'From the Photos share sheet, JXL-Import then saves the results. Started any '
        'other way, it shows a photo picker (which gives the original HEIF files), '
        'saves the results itself. Either way, the converted originals go into the '
        f'album "{ORIGINALS_ALBUM}" for you to review; nothing is deleted. '
        "each JPEG XL copy is also added to its original's albums. "
        'Setup and help: '
        f'{HELP_URL}'
    )
    b.if_has_value(
        SHORTCUT_INPUT,
        lambda: b.set_variable('Photos', SHORTCUT_INPUT),
        lambda: b.set_variable('Photos', b.select_photos()),
    )
    # From here on only the still photos: they are staged, and their positions
    # in Stills are the job indices, also when saving the results.
    photos = keep_still_photos(b, variable('Photos'))
    quality = choose_quality(b)
    # A stale album file from an unfinished run would put a photo into the
    # wrong albums; jxl_in_* files are overwritten anyway.
    b.ashell_execute(
        'rm -f jxl_done.txt jxl_out_* jxl_albums_* jxl_started',
        keep_going=True,
        open_app='close',
    )

    # Only the original file goes to a-Shell: jxlbatch decodes HEIF, JPEG and
    # PNG itself, so there is no Convert Image step.
    def per_photo():
        name = b.get_name(REPEAT_ITEM)
        b.ashell_put_file(
            b.set_name(REPEAT_ITEM, 'jxl_in_', REPEAT_INDEX, '.orig')
        )
        b.append_variable('Jobs', b.text(REPEAT_INDEX, '|', name))

    b.repeat_each(photos, per_photo)
    b.ashell_put_file(
        b.set_name(b.combine(variable('Jobs'), '\n'), 'jxl_job.txt')
    )

    def from_share_sheet():
        # A share-sheet shortcut can't resume after a-Shell: JXL-Import saves,
        # and it no longer has the originals. So their album names go to
        # a-Shell too, as jxl_albums_<i>.txt (same order as jxl_in_<i>.orig).
        def write_albums():
            albums = b.photo_albums(REPEAT_ITEM)
            b.if_has_value(
                albums,
                lambda: b.ashell_put_file(
                    b.set_name(
                        b.combine(albums, '\n'),
                        'jxl_albums_',
                        REPEAT_INDEX,
                        '.txt',
                    )
                ),
                lambda: None,
            )

        b.repeat_each(photos, write_albums)
        # The originals are collected now: once a-Shell is in front this
        # shortcut is over, and JXL-Import has no originals. So a photo whose
        # conversion fails is in the album too; a-Shell's output names it.
        album = b.text(ORIGINALS_ALBUM)
        b.repeat_each(photos, lambda: collect_in_album(b, REPEAT_ITEM, album))
        run_jxlbatch(
            b, quality, f'open shortcuts://run-shortcut?name={NAME_B}'
        )

    def from_picker():
        run_jxlbatch(b, quality, 'open shortcuts://')
        b.wait_to_return()
        album = b.text(ORIGINALS_ALBUM)
        count = save_results(b, photos, album)
        b.ashell_execute(CLEANUP, keep_going=True, open_app='close')
        # Empty when nothing was saved, or every original was in the album.
        b.if_has_value(
            variable('Collected'),
            lambda: b.notification(
                'JPEG XL',
                'Saved ',
                count,
                ' photo(s) to Photos. ',
                b.count(variable('Collected')),
                f' original(s) are in the album "{ORIGINALS_ALBUM}" for you to review.',
            ),
            lambda: b.notification(
                'JPEG XL', 'Saved ', count, ' photo(s) to Photos.'
            ),
        )

    b.if_has_value(SHORTCUT_INPUT, from_share_sheet, from_picker)
    return b.actions


def build_import(sample):
    b = Builder(sample)
    b.comment(
        f'{NAME_B} ({NAME_A} {VERSION}). '
        'Started by a-Shell when jxlbatch finishes. Saves the converted JPEG XL '
        'files to Photos. Keep this name: a-Shell starts it by name.'
    )
    count = save_results(b)
    b.ashell_execute(CLEANUP, keep_going=True, open_app='close')
    b.notification('JPEG XL', 'Saved ', count, ' photo(s) to Photos.')
    return b.actions


def write(name, workflow_dict, sign):
    wf.write(name, workflow_dict, sign, OUT, DIST)


def main():
    ap = argparse.ArgumentParser(
        description=__doc__,
        formatter_class=argparse.RawDescriptionHelpFormatter,
    )
    ap.add_argument(
        '--fetch',
        metavar='ICLOUD_LINK',
        help='download the sample shortcut from its iCloud link',
    )
    ap.add_argument(
        '--no-sign', action='store_true', help='write unsigned plists only'
    )
    ap.add_argument(
        '--sample',
        type=Path,
        default=SAMPLE,
        help='sample shortcut plist to use',
    )
    ap.add_argument(
        '--guess',
        action='store_true',
        help='use hand-written action templates instead of a sample (best guess)',
    )
    args = ap.parse_args()
    if args.fetch:
        fetch_sample(args.fetch)

    if args.guess:
        sample = Sample(guessed_workflow())
    elif not args.sample.exists():
        sys.exit(
            f'missing {args.sample}: run with --fetch <iCloud link of the sample shortcut>, or --guess'
        )
    else:
        sample = Sample(args.sample)

    write(
        NAME_A,
        workflow(sample, NAME_A, build_compress(sample), share_sheet=True),
        not args.no_sign,
    )
    write(
        NAME_B,
        workflow(sample, NAME_B, build_import(sample), share_sheet=False),
        not args.no_sign,
    )


if __name__ == '__main__':
    main()
